#!/usr/bin/env bash
# Linux netboot lab for the Medea provisioning E2E (design/provisioning-plane.md
# §12). Brings up an isolated bridge with dnsmasq (DHCP + TFTP/iPXE) and
# Matchbox, and PXE-boots QEMU nodes off it. Run on a Linux host with QEMU; on
# macOS it runs inside a Linux VM (see run.sh — `make test-netboot`).
#
# It is arch-aware: ARCH defaults to the host arch (arm64 on an M-series Mac's
# Linux VM, amd64 in CI). The logic under test is arch-independent; the Beelinks
# remain the amd64 truth.
#
# Subcommands:
#   deps        apt-install qemu, dnsmasq, ipxe, edk2 firmware, matchbox
#   up          create the bridge, start dnsmasq + matchbox
#   boot <mac> <name> [disk]   PXE-boot a QEMU node on the bridge (background)
#   down        stop everything, delete the bridge, remove the workdir
#   ip          print the bridge/matchbox host IP
#
# Env (override as needed):
#   ARCH          amd64 | arm64           (default: host arch)
#   BR            bridge name             (default: medeabr0)
#   SUBNET        lab subnet              (default: 10.66.0)
#   WORKDIR       lab state dir           (default: /tmp/medea-netboot)
#   MEM           node memory MB          (default: 3072)
set -euo pipefail

ARCH="${ARCH:-$(uname -m)}"
case "$ARCH" in
x86_64 | amd64) ARCH=amd64 ;;
aarch64 | arm64) ARCH=arm64 ;;
*) echo "unsupported ARCH=$ARCH" >&2; exit 1 ;;
esac

BR="${BR:-medeabr0}"
SUBNET="${SUBNET:-10.66.0}"
GW_IP="${SUBNET}.1"
WORKDIR="${WORKDIR:-/tmp/medea-netboot}"
MEM="${MEM:-3072}"
MB_DIR="$WORKDIR/matchbox"          # Matchbox -data-path (Medea's driver writes here)
MB_ASSETS="$WORKDIR/matchbox/assets"
TFTP_DIR="$WORKDIR/tftp"
MATCHBOX_URL="http://${GW_IP}:8080"

log() { echo ">> $*" >&2; }

cmd_ip() { echo "$GW_IP"; }

cmd_deps() {
  log "installing lab dependencies (apt)"
  sudo apt-get update -qq
  # qemu (full system + the arch we target), dnsmasq, ipxe bootloaders, UEFI fw.
  local pkgs=(dnsmasq ipxe qemu-utils curl ca-certificates)
  if [ "$ARCH" = amd64 ]; then
    pkgs+=(qemu-system-x86 ovmf)
  else
    pkgs+=(qemu-system-arm qemu-efi-aarch64)
  fi
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq "${pkgs[@]}"
  install_matchbox
}

install_matchbox() {
  if command -v matchbox >/dev/null 2>&1 || [ -x "$WORKDIR/bin/matchbox" ]; then
    return
  fi
  log "downloading matchbox binary"
  mkdir -p "$WORKDIR/bin"
  local ver=v0.11.0
  curl -fsSL "https://github.com/poseidon/matchbox/releases/download/${ver}/matchbox-${ver}-linux-${ARCH}.tar.gz" \
    | tar -xz -C "$WORKDIR/bin" --strip-components=1 "matchbox-${ver}-linux-${ARCH}/matchbox"
}

matchbox_bin() { command -v matchbox 2>/dev/null || echo "$WORKDIR/bin/matchbox"; }

cmd_up() {
  mkdir -p "$MB_DIR/groups" "$MB_DIR/profiles" "$MB_DIR/generic" "$MB_ASSETS" "$TFTP_DIR"

  # UEFI iPXE loader for the arch (the ipxe apt package ships per-arch EFI files);
  # the QEMU nodes boot UEFI, so we only need the .efi loader.
  cp -f "/usr/lib/ipxe/ipxe-${ARCH}.efi" "$TFTP_DIR/ipxe.efi"

  log "creating bridge $BR ($GW_IP/24)"
  sudo ip link add name "$BR" type bridge 2>/dev/null || true
  sudo ip addr add "$GW_IP/24" dev "$BR" 2>/dev/null || true
  sudo ip link set "$BR" up

  write_dnsmasq_conf
  log "starting dnsmasq on $BR"
  sudo pkill -F "$WORKDIR/dnsmasq.pid" 2>/dev/null || true
  sudo dnsmasq --conf-file="$WORKDIR/dnsmasq.conf" --pid-file="$WORKDIR/dnsmasq.pid"

  log "starting matchbox (data=$MB_DIR, url=$MATCHBOX_URL)"
  pkill -F "$WORKDIR/matchbox.pid" 2>/dev/null || true
  "$(matchbox_bin)" -address="0.0.0.0:8080" -data-path="$MB_DIR" -assets-path="$MB_ASSETS" -log-level=debug \
    >"$WORKDIR/matchbox.log" 2>&1 &
  echo $! >"$WORKDIR/matchbox.pid"

  log "lab up. matchbox=$MATCHBOX_URL  data-path=$MB_DIR"
}

write_dnsmasq_conf() {
  # UEFI arch tag (DHCP option 93): 7/9 = x86-64, 11 = arm64.
  local uefi_tag
  [ "$ARCH" = amd64 ] && uefi_tag="efi64" || uefi_tag="efiarm"
  cat >"$WORKDIR/dnsmasq.conf" <<EOF
# Generated by lab.sh — full DHCP (isolated bridge) + TFTP/iPXE -> Matchbox.
port=0
log-dhcp
interface=$BR
bind-interfaces
except-interface=lo

dhcp-range=${SUBNET}.10,${SUBNET}.100,12h
dhcp-option=option:router,${GW_IP}
dhcp-option=option:dns-server,1.1.1.1

enable-tftp
tftp-root=$TFTP_DIR

dhcp-userclass=set:ipxe,iPXE
dhcp-match=set:efi64,option:client-arch,7
dhcp-match=set:efi64,option:client-arch,9
dhcp-match=set:efiarm,option:client-arch,11

# Stage 1: bare UEFI firmware -> chainload iPXE over TFTP.
dhcp-boot=tag:!ipxe,tag:$uefi_tag,ipxe.efi
# Stage 2: now running iPXE -> hand off to Matchbox.
dhcp-boot=tag:ipxe,$MATCHBOX_URL/boot.ipxe
EOF
}

# boot <mac> <name> [disk-size] — PXE-boot a QEMU node on the bridge.
cmd_boot() {
  local mac="$1" name="$2" disk_size="${3:-10G}"
  local tap="tap-${name}"
  local disk="$WORKDIR/${name}.qcow2"
  [ -f "$disk" ] || qemu-img create -f qcow2 "$disk" "$disk_size" >/dev/null

  sudo ip tuntap add dev "$tap" mode tap 2>/dev/null || true
  sudo ip link set "$tap" master "$BR"
  sudo ip link set "$tap" up

  local qemu fw_args=()
  if [ "$ARCH" = amd64 ]; then
    qemu=qemu-system-x86_64
    fw_args=(-machine q35 -cpu max -bios "${OVMF:-/usr/share/OVMF/OVMF.fd}")
  else
    qemu=qemu-system-aarch64
    fw_args=(-machine virt -cpu max -bios /usr/share/qemu-efi-aarch64/QEMU_EFI.fd)
  fi

  log "booting node $name (mac=$mac, arch=$ARCH, TCG=no-KVM may be slow)"
  sudo "$qemu" "${fw_args[@]}" \
    -m "$MEM" -smp 2 -nographic \
    -drive file="$disk",if=virtio,format=qcow2 \
    -netdev tap,id=n0,ifname="$tap",script=no,downscript=no \
    -device virtio-net-pci,netdev=n0,mac="$mac" \
    -boot n \
    >"$WORKDIR/${name}.console.log" 2>&1 &
  echo $! >"$WORKDIR/${name}.pid"
}

cmd_down() {
  log "tearing down lab"
  for p in "$WORKDIR"/*.pid; do [ -f "$p" ] && { sudo pkill -F "$p" 2>/dev/null || true; }; done
  sudo pkill -F "$WORKDIR/dnsmasq.pid" 2>/dev/null || true
  for t in $(ip -o link show | awk -F': ' '/tap-/{print $2}' | cut -d@ -f1); do
    sudo ip link del "$t" 2>/dev/null || true
  done
  sudo ip link del "$BR" 2>/dev/null || true
  rm -rf "$WORKDIR"
}

case "${1:-}" in
deps) cmd_deps ;;
up) cmd_up ;;
boot) shift; cmd_boot "$@" ;;
down) cmd_down ;;
ip) cmd_ip ;;
*) echo "usage: $0 {deps|up|boot <mac> <name> [disk]|down|ip}" >&2; exit 2 ;;
esac
